name = "Test Server"
author = "Crispy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f6e6d17effceb43e374fda37bd1b1bf98e27e7bf6af06d358dbf5d256648a24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
