name = "Test Server"
author = "Crispy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb380fac0ec9fb9195d514378f757104860dfbcb56976244138c2f189df250bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
